name: unique
version: @version@
main: com.github.azuazu3939.unique.Unique
bootstrapper: com.github.azuazu3939.unique.Bootstrap
api-version: '1.21'
folia-supported: true
load: POSTWORLD
authors: [ MCLove32 ]
website: https://github.com/azuazu3939

dependencies:
  server:
    packetevents:
      load: BEFORE

permissions:
  unique.use:
    description: Allows use of unique commands
    default: true
  unique.spawn:
    description: Allows spawning custom mobs
    default: op
  unique.reload:
    description: Allows reloading the plugin configuration
    default: op
