name: unique
version: @version@
main: com.github.azuazu3939.unique.Unique
bootstrapper: com.github.azuazu3939.unique.Bootstrap
api-version: '1.21'
folia-supported: true
load: STARTUP
authors: [ MCLove32 ]
website: https://github.com/azuazu3939

dependencies:
  server:
    packetevents:
      load: BEFORE

# Permissions
permissions:
  unique.command:
    description: Access to Unique commands
    default: op
  unique.reload:
    description: Reload plugin configuration
    default: op
  unique.spawn:
    description: Spawn custom mobs
    default: op
  unique.debug:
    description: Access debug commands
    default: op